// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CODE_SERIES.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240307093713_TestjohnOnModelCreating")]
    partial class TestjohnOnModelCreating
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Student", b =>
                {
                    b.Property<Guid>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("65ce7d12-416b-4f27-89b8-0cb8d5e611be"),
                            Age = 30,
                            Name = "John Doe"
                        },
                        new
                        {
                            StudentId = new Guid("0e5c1f86-84c6-46ca-be00-8736659a694c"),
                            Age = 25,
                            Name = "Jane Doe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
